---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks: 
     - name: Start httpd server on Host Machines
       action: service name=httpd state=started
      
     - name: Clone Flipkart Clone repo
       git:
          repo: https://github.com/Msocial123/Flipkart-Clone.git
          dest: index.html
          version: main
          force: yes