--- 
- hosts: webservers 
  user: ansible 
  become: yes 
  connection: ssh 
  tasks: 
    - name: I want to Install git,python,java in Host Machines
      action: yum pkg='{{item}}' state=present 
      loop:
        - git
        - python3
        - java-17-amazon-corretto.x86_64